name: GVA Cita Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *" # cada 15 minutos

jobs:
  check:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps chromium firefox

      - name: Run checker
        env:
          GVA_BASE: "https://sige.gva.es/qsige/citaprevia.justicia"
          APPOINTMENT_UUID: ${{ secrets.APPOINTMENT_UUID }}
          # O bien puedes usar directamente APPOINTMENT_URL en lugar del UUID:
          # APPOINTMENT_URL: ${{ secrets.APPOINTMENT_URL }}

          CENTRO_TEXT: ${{ secrets.CENTRO_TEXT }}
          SERVICIO_TEXT: ${{ secrets.SERVICIO_TEXT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          HEADLESS: "true"
          TIMEOUT_MS: "180000"
          BROWSER_CHANNEL: "chrome"
        run: |
          npm run check

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gva-debug
          path: |
            *.png
            *.html
            videos/
            traces/
