name: GVA Cita Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *" # cada 15 minutos (UTC)

jobs:
  check:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ---------- WINDOWS ----------
      - name: Install deps (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          IF EXIST package-lock.json (
            npm ci
          ) ELSE (
            npm install
          )
          REM Asegura que el paquete 'playwright' esté instalado
          npm i -D playwright@latest
          REM Instala navegadores necesarios
          npx playwright install chromium firefox

      # ---------- LINUX / macOS ----------
      - name: Install deps (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
          npm i -D playwright@latest
          npx playwright install --with-deps chromium firefox

      - name: Run checker
        env:
          # Deep-link directo a la pantalla de cita (opcional, recomendado)
          GVA_BASE: "https://sige.gva.es/qsige/citaprevia.justicia"
          APPOINTMENT_UUID: ${{ secrets.APPOINTMENT_UUID }}
          # O usa APPOINTMENT_URL directamente si lo prefieres:
          # APPOINTMENT_URL: ${{ secrets.APPOINTMENT_URL }}

          # Selección y notificaciones
          CENTRO_TEXT: ${{ secrets.CENTRO_TEXT }}
          SERVICIO_TEXT: ${{ secrets.SERVICIO_TEXT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

          # Ejecución
          HEADLESS: "false"          # pon "true" si no quieres que se abra la ventana
          TIMEOUT_MS: "180000"
          BROWSER_CHANNEL: "chrome"  # si usas el script con Chromium/Chrome
        run: npm run check

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gva-debug
          path: |
            *.png
            *.html
            videos/
            traces/
          if-no-files-found: ignore
