name: GVA Cita Checker
on:
  schedule:
    - cron: "*/30 * * * *"  # Cada 30 minutos (UTC)
  workflow_dispatch:

jobs:
  check:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Instalación de dependencias en Windows
      - name: Install deps (Windows)
        if: runner.os == 'Windows'
        run: |
          npm install
          npx playwright install

      # Instalación de dependencias en Linux/macOS
      - name: Install deps (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          npm install
          npx playwright install --with-deps

      # Ejecución del script principal
      - name: Run checker
        env:
          CENTRO_TEXT: ${{ secrets.CENTRO_TEXT }}
          SERVICIO_TEXT: ${{ secrets.SERVICIO_TEXT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TIMEOUT_MS: "180000"
          HEADLESS: "false"         # Muestra el navegador real (útil para depurar)
          BROWSER_CHANNEL: "chrome" # Usa Google Chrome instalado en tu PC
        run: npm run check

      # Subida de capturas, HTML, trazas y vídeos para depurar
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gva-debug
          path: |
            home*.png
            home*.html
            after_cta*.png
            after_cta*.html
            after_cta_iframe.html
            state.png
            videos/**
            traces/trace.zip
          if-no-files-found: ignore
